### ISSUE TITLE
`testEnvironment: 'jsdom'` in my jest.config.js not work..

### ISSUE THREAD

**Issue by davych** [jimzhan/esnext-scripts#3]
Hello boss jim, I found the `testEnvironment` is hardcode in your etc/jest.config file.  so I can't use 'jsdom' in my jest.config.js when I use esnext test.  can you improve it ?

**Comment by jimzhan** [comment]
custom settings supported via (by order):

- <cwd>/jest.config.js
- <cwd>/package.json#jest
